# On active la scalabilité HPA !
# HPA = horizontal pod autoscaling
# Ça évite d'utiliser trop de resources pour rien !
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nuit-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nuit-api
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50