name: build et déploie l'api sur le cluser k8s
on:
  push:
    branches:
      - 'main'

jobs:
  build-deploie:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: QEMU
        uses: docker/setup-qemu-action@v1

      - name: Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: DockerHub
        uses: docker/login-action@v1

        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build et déploiement
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: aimerisson/nuit-info:latest

  deploiement-api-cluster:
    runs-on: ubuntu-latest
    needs: [build-deploie]
    steps:

        - name: Checkout
          uses: actions/checkout@v2

        - name: kubeconfig
          uses: azure/k8s-set-context@v2
          with:
            method: kubeconfig
            kubeconfig: ${{ secrets.KUBECONFIG }}

        - name: deploiement sur le cluster
          uses: jtalk/k8s-deploy@v2
          with:
            namespace: 'nuit-info'
            manifests: |
              ${{ github.workspace }}/k8s/api.yaml
              ${{ github.workspace }}/k8s/autoscale.yaml